### ISSUE TITLE
【期末考试】2018/03/13-2018/03/25

### ISSUE THREAD

**Issue by mrzhqiang** [mrzhqiang/studyjava-zz#100]
# 背景
共同学习Java有四个月时间，地基已打好，那么首先回顾知识点：

- 什么是Java？

- 开发环境配置：JDK+IntelliJ IDEA。

- 程序设计结构：通过操作哪些元素来设计一个程序？

    - 数据类型：整数、浮点数、字符、布尔类型。
    - 变量：初始化和常量。
    - 运算符：加减乘除、数值转换、类型转换、自增和自减、关系和布尔运算、位运算、括号相关、取模、三元运算、枚举类型。
    - 字符串：文字的裁缝。
    - 输入输出流：在屏幕上、文件中，进行输入输出操作。
    - 控制流程：语句块、条件、循环、多重选择、中断语句，扩展训练：枚举与多重循环。
    - 数组：初始化、遍历、排序、多维数组。

- 类和对象：类的设计（扩展：23种设计模式）、预定义类、自定义类、静态相关、方法参数、构造器、包、路径、文档注释。

- 继承和多态：超类和子类、继承与多态、泛型数组、包装器和自动装箱、反射。

- 接口和内部类：接口的应用场景、内部类的存在意义，扩展：lambda表达式、代理。

- 异常：为什么要捕获异常？捕捉异常显而易见的好处是？

- 集合：List、Set、Map的使用场合，扩展：映射、视图与包装器、算法、遗留的集合。

- 并发：线程的创建方法、线程池的意义、线程的几种状态、为什么要进行同步、线程安全的集合、Callable与Future、执行器、同步器。

# 进阶
事实上，从入门到精通这本书讲得太浅显，不足以勾勒出java的全部轮廓。当然，核心技术这本书是神书，大部分三年左右的开发者，也都在跟着学习。所以不要有任何压力，强迫自己去记忆。这些都是日积月累的，不需要一次性学完就不管了，应试教育最悲哀的地方就是，学完考完就丢掉了。

实践中需要自学的知识点：

- 泛型
- 单元测试

# 关于考试
将根据以上知识点设计考试题目，题目属于实践操作，不存在百度出来一模一样的题目和答案，纯脑力活。当然，相关知识点和概念，从书中和百度肯定可以找到，这也是程序猿最喜欢的方式（最无聊的方式）。

**Comment by YouKuanZeng** [comment]
动手能力差的人表示，出题吧，边做边爱（fuxi）对不对？

**Comment by mrzhqiang** [comment]
@YouKuanZeng  时间，延长到这周，最近比较忙，题目还没弄。

**Comment by mrzhqiang** [comment]
## 项目需求
1. 设计一个简单的抽奖积分系统
2. 设计一个简单的账号登陆系统
3. 验证普通排序、冒泡排序、选择排序、快速排序，各自的性能

## 设计规范

#### 抽奖
1. 设置一等奖、二等奖、三等奖，奖励积分分别是1000、200、100，中奖几率为1/100、1/50、1/20，另外设一个安慰奖，表示可以再抽一次，几率是1/10
2. 抽奖的基本逻辑是，每个账号的初始积分是1000分，50分可以抽一次奖，奖励的积分将计入账号内
3. 扩展训练是，持久化账号信息，将积分和用户名，写入到文件中

#### 账号
1. 使用数据库持久化账号信息，首先注册账号，账号由username和password组成，额外增加一个mobile字段，表示可以用手机号注册
2. 要求验证username长度为6-16位，密码随机生成，也是6-16位，mobile使用正则表达式验证，网上可以抄袭到

#### 排序
1. 首先生产100万--2000万条数据，类型为double，无符号，数值从0到1000之间随机诞生，存储在数组中
2. 编写四种排序的静态方法：[点击查看排序算法](https://www.cnblogs.com/onepixel/articles/7674659.html)
3. 打印调用这些排序方法所消耗的时间，``System.currentTimeMillis()``表示获得系统当前毫秒时间（自1970年初到现在经历过的时间毫秒值）
4. 扩展训练：使用多线程同时跑排序算法

**Comment by mrzhqiang** [comment]
排序的补充：使用冒泡、选择、快速、插入，数据量是10万，由我来生产，并制作数组储存。

**Comment by YouKuanZeng** [comment]
## 反馈：
- 枯坐一天还是没有完成任何一个题目，每每去实现这些东西，会出现很多细节小问题，可能还是缺乏兴趣，做着一段时间，便感觉耐心耗尽。自觉又无法完成任务了。
- 本想做完这些题目，再跟你说这事的，没做完题目总觉得对不住你，不好意思说，但现在也只能厚着脸皮说了，因为自己的原因吧，也可能跟家里有关，拉上女票报了4月21号的公务员考试，想去尝试一下。
- 跟你学java，其实就是怕被排挤到社会边缘，被淘汰，跟不上这世界的速度，也不知道去考这个对不对，毕竟又是体制内，终归报了名，就搏一搏。
- 倒不是说要结束这样的学习。一直以来的依赖和拖沓，还是让你付出了太多的精力，总觉得我自己的事情，你比我上心多了。嗯，考完试我还是要继续学习的。就是真的发现自己太不自律也太少耐心，我是适合干什么呢？
- 明天晚上，你如果有空，你可以讲解一下这些题目吗？看别人做总觉得简单，自己动手就错误百出的节奏。

**Comment by YouKuanZeng** [comment]
- 听完这课，然后，就开始备考了。

**Comment by YouKuanZeng** [comment]
- 听完这课，然后，就开始备考了。

**Comment by mrzhqiang** [comment]
题目可以讲解。所以你又遇到了西瓜，准备丢弃这个芝麻？等西瓜你抱不动了，估计又要回来捡。但已经不可能捡到了。

**Comment by YouKuanZeng** [comment]
好呀好呀，28号，30号晚上都行，看你的空闲。公务员不是西瓜，java这也不是芝麻，我倒是只猴子。只是尝试，认真考试一下罢了。回不回得来我不知道，但人终归还是得学习，不管是学习java还是去学别的，不管学会没学会。我还是太喜欢舒适区了。

**Comment by mrzhqiang** [comment]
10万条数据的情况下：
冒泡——17646 ms
选择——4238 ms
插入——816 ms
快速——29 ms

**Comment by mrzhqiang** [comment]
close all question
