### ISSUE TITLE
日程表

### ISSUE THREAD

**Issue by YouKuanZeng** [mrzhqiang/studyjava-zz#16]
学习情况反馈：
1. 完成第三章总结以及思维导图。并在总结中提出了一些疑惑，还请@mrzhqiang解答。
2. 重看了第三章录制的讲解视频。
学习感想：
1. 基础知识还是掌握的很不牢靠，需要多敲代码多熟练。
2017.11.28  java学习第16天计划
8：00-21：30上班，休息时间看《JAVA从入门到精通》电子书
21：30-23：00完成第三章程序清单或请mrzhqiang讲课。

**Comment by YouKuanZeng** [comment]
# 2017.11.29 java学习第17天
###  11.28 学习情况：
- 观摩mrzhqiang示范一个简单的计算器程序编写。
### 学习计划：
- 9：00 —— 12：00 自己动手敲一遍简单的计算器程序编写。
- 14：30 —— 17:30 自习看书，手打一遍程序清单。

**Comment by YouKuanZeng** [comment]
# 2017.11.30 java学习第18天
### 11.29 学习情况：
- 简单计算器的编写，有很多思维打不开，逻辑不对，还需要大幅改进；
- 完成范例1（3.5.9）和范例2（3.5.10）；
- 对于mrzhqiang的不带图和具体事例的术语提示表示无感。
### 学习计划
- 16：00 - 17：30 看书
- 20：00 - 23：00 手打程序清单

**Comment by YouKuanZeng** [comment]
# 简单计算器
- 尚有很多不足，逻辑不清，代码繁琐，功能单一，个人人为以后可以持续改进。请@mrzhqiang提议。
- [Calculator](https://github.com/mrzhqiang/studyjava-zz/tree/master/project/%E3%80%8AJava%E6%A0%B8%E5%BF%83%E6%8A%80%E6%9C%AF%E3%80%8B/%E7%AC%AC%E4%B8%89%E7%AB%A0/YouKuanZeng/%20Calculator)

**Comment by YouKuanZeng** [comment]
# 2017.12.01 java学习第19天
### 11.30学习情况：
- 完成JAVA核心技术第三章程序清单1-5
###  学习计划：
- 回衡阳，带书边走边看。算是放假了，哈哈。

**Comment by YouKuanZeng** [comment]
# 2017.12.02 java学习第20天
###  12.01学习情况：
- 完成Java从入门到精通前三章简览
### 学习计划：
- 21：30  - 23：00完成Java从入门到精通第4章到第六章的简单阅读

**Comment by mrzhqiang** [comment]
越来越长，有点麻烦。单个日程，单个ISSUE

**Comment by YouKuanZeng** [comment]
OK
