### ISSUE TITLE
《Java从入门到精通》范例

### ISSUE THREAD

**Issue by mrzhqiang** [mrzhqiang/studyjava-zz#17]
# 第3章 Java语言基础
### 范例1
不用其他变量实现两变量互换
### 范例2
判断数字的奇偶性

**Comment by mrzhqiang** [comment]
[完成测试](https://github.com/mrzhqiang/studyjava-zz/tree/master/project/%E3%80%8AJava%E6%A0%B8%E5%BF%83%E6%8A%80%E6%9C%AF%E3%80%8B)

**Comment by YouKuanZeng** [comment]
###范例1[https://github.com/mrzhqiang/studyjava-zz/tree/master/project/%E3%80%8AJava%E6%A0%B8%E5%BF%83%E6%8A%80%E6%9C%AF%E3%80%8B/%E7%AC%AC%E4%B8%89%E7%AB%A0/YouKuanZeng/example3_5_10](url)

**Comment by YouKuanZeng** [comment]
###  [范例1] <https://github.com/mrzhqiang/studyjava-zz/tree/master/project/%E3%80%8AJava%E6%A0%B8%E5%BF%83%E6%8A%80%E6%9C%AF%E3%80%8B/%E7%AC%AC%E4%B8%89%E7%AB%A0/YouKuanZeng/example3_5_10 >

**Comment by YouKuanZeng** [comment]
### 范例2[https://github.com/mrzhqiang/studyjava-zz/tree/master/project/%E3%80%8AJava%E6%A0%B8%E5%BF%83%E6%8A%80%E6%9C%AF%E3%80%8B/%E7%AC%AC%E4%B8%89%E7%AB%A0/YouKuanZeng/example3_5_10](url)

**Comment by YouKuanZeng** [comment]
[范例](https://github.com/mrzhqiang/studyjava-zz/tree/master/project/%E3%80%8AJava%E6%A0%B8%E5%BF%83%E6%8A%80%E6%9C%AF%E3%80%8B/%E7%AC%AC%E4%B8%89%E7%AB%A0/YouKuanZeng/example3_5_10 )

**Comment by YouKuanZeng** [comment]
# 2017.11.29完成范例
- [范例1](https://github.com/mrzhqiang/studyjava-zz/tree/master/project/%E3%80%8AJava%E6%A0%B8%E5%BF%83%E6%8A%80%E6%9C%AF%E3%80%8B/%E7%AC%AC%E4%B8%89%E7%AB%A0/YouKuanZeng/example3_5_9)
- [范例2](https://github.com/mrzhqiang/studyjava-zz/tree/master/project/%E3%80%8AJava%E6%A0%B8%E5%BF%83%E6%8A%80%E6%9C%AF%E3%80%8B/%E7%AC%AC%E4%B8%89%E7%AB%A0/YouKuanZeng/example3_5_10)

**Comment by mrzhqiang** [comment]
范例1运行通过，但是项目打开时存在问题：多出来一个src目录。

**Comment by mrzhqiang** [comment]
范例2运行通过，没有问题。

**Comment by YouKuanZeng** [comment]
#2017.11.30完成范例
- [CoreJava第三章程序清单1-5](https://github.com/mrzhqiang/studyjava-zz/tree/master/project/%E3%80%8AJava%E6%A0%B8%E5%BF%83%E6%8A%80%E6%9C%AF%E3%80%8B/%E7%AC%AC%E4%B8%89%E7%AB%A0/YouKuanZeng)

**Comment by mrzhqiang** [comment]
OK
