### ISSUE TITLE
第四周（2017 12/04——2017 12/10）

### ISSUE THREAD

**Issue by mrzhqiang** [mrzhqiang/studyjava-zz#21]
#### 关于面向对象
- 面向对象
- 对象是什么
- 类是什么
- 面向对象有什么特点
#### 关于类
- 构造
- 方法
- 成员
- 权限
- 范例与思路
#### 关于对象
- 创建
- 访问
- 引用相关
- 比较相关
- 迷之销毁
- 范例与思路
#### 实践与任务
- 设计模式之单实例

**Comment by mrzhqiang** [comment]
@YouKuanZeng  简单浏览下？

**Comment by mrzhqiang** [comment]
#### 设计模式之单实例
这部分需要理解的范围稍微宽泛，单实例是指：程序（main）中只存在一个实例（对象），如果使用某些技巧（思路：不能直接用new关键字去创建这个实例，可以使用类方法+静态变量，也就是静态方法+静态变量去做）。
前提：例子/范例/实战练习都完成了，才去做这个学习任务。

**Comment by YouKuanZeng** [comment]
简单的听你说过了，等待自虐……

**Comment by mrzhqiang** [comment]
单例模式啊啊啊啊 还有2天结束这周计划

**Comment by YouKuanZeng** [comment]
- [单例模式](https://github.com/mrzhqiang/studyjava-zz/tree/master/project/%E3%80%8Ajava%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E7%B2%BE%E9%80%9A%E3%80%8B/zyk_java7_single)
- 来啊，反正还不完全懂

**Comment by mrzhqiang** [comment]
OK
