### ISSUE TITLE
准备血虐少年

### ISSUE THREAD

**Issue by mrzhqiang** [mrzhqiang/studyjava-zz#22]
鉴于学习进度的一再拖拉，尽管是小白，但也要被血虐一次，然后再阅读这些章节，想必有一些收获。
另外由于本人教学水平不足，只能借鉴应试教育的先进性，将尝试一下填鸭式教学。

**Comment by YouKuanZeng** [comment]
I'm ready.Come baby.

**Comment by mrzhqiang** [comment]
OK
