### ISSUE TITLE
2017.12.04 日程表

### ISSUE THREAD

**Issue by YouKuanZeng** [mrzhqiang/studyjava-zz#23]
###  学习反馈：
- 无
### 学习安排：
- 16：00 - 18：00 继续阅读
- 19：00 - 23：00手打范例或者等待血洗

**Comment by mrzhqiang** [comment]
我还在等台式机网络的解决，你可以先看光盘里的视频。

**Comment by mrzhqiang** [comment]
网络已经解决，晚上开始血虐。

**Comment by mrzhqiang** [comment]
完成了血虐
