### ISSUE TITLE
《Java从入门到精通》第七章作业

### ISSUE THREAD

**Issue by mrzhqiang** [mrzhqiang/studyjava-zz#25]
### 例子
- 7.1 无参构造方法和有参构造方法；this调用其他构造方法
- 7.2 主方法（可以认为是一个程序）的传参，是通过例子中的Eclipse设置
- 7.3 建立类似于书中的Book类，叫Phone的类，简单一点就好
- 7.4 局部变量
- 7.5 使用静态成员，输出一个圆面积的计算
- 7.6 参照例子，调用7.5新设计的方法
- 7.7/7.8 玩一下访问权限修饰符，总共有4种
- 7.9/7.10 get和set方法的手打
- 7.11 （后面遇到特殊例子需要改动的时候，再写出来）
- 7.13 自己研究为什么书上有错误

### 范例
- 范例1 手打，然后扩展练习为：Phone
- 范例2 手打
- 范例3 扩展为：Phone的销量

### 实战练习

**Comment by YouKuanZeng** [comment]
### 2017.12.05
- (部分完成)[https://github.com/mrzhqiang/studyjava-zz/tree/master/project/%E3%80%8Ajava%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E7%B2%BE%E9%80%9A%E3%80%8B]

**Comment by YouKuanZeng** [comment]
### 2017.12.05
- [部分范例](https://github.com/mrzhqiang/studyjava-zz/tree/master/project/%E3%80%8Ajava%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E7%B2%BE%E9%80%9A%E3%80%8B)

**Comment by mrzhqiang** [comment]
今天晚上检查作业

**Comment by YouKuanZeng** [comment]
- [所有范例](https://github.com/mrzhqiang/studyjava-zz/tree/master/project/%E3%80%8Ajava%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E7%B2%BE%E9%80%9A%E3%80%8B)
- 还是很多迷茫吧，还是有很多剩饭要嚼，还有很多锅要背，还有很多背锅的时候要逃。

**Comment by mrzhqiang** [comment]
“今天”终于来过一遍作业了。
