### ISSUE TITLE
2017年12月

### ISSUE THREAD

**Issue by mrzhqiang** [mrzhqiang/studyjava-zz#31]
接口/继承/多态，类的高级特性，集合，结合数组一起看看。
输入输出和文件系统一起讲，顺便把字符串再回顾一下。
多线程和网络通信一起讲，顺便看看异常处理。

**Comment by YouKuanZeng** [comment]
接口，继承，多态，还是进行时哇……

**Comment by mrzhqiang** [comment]
26号简单讲一下网络通信，之后有时间，一起看范例，回顾之前的知识，巩固一下记忆。
其实，最好的情况是，一起做简单的项目，更容易回顾。
