### ISSUE TITLE
关于自主学习推荐的社区

### ISSUE THREAD

**Issue by YouKuanZeng** [mrzhqiang/studyjava-zz#4]
你说知乎吹牛比较多，简书里面太多鸡汤，还有几个社区需要我记得来着，可是我忘了。 @mrzhqiang

**Comment by mrzhqiang** [comment]
简书不是太多鸡汤，而是你需要在鸡汤的重重包围中，寻找知识的力量；掘金社区还不错，很多文章都是翻译自国外。这两个都可以下载app，没事就可以去灌输下真气。

**Comment by YouKuanZeng** [comment]
好吧，开始筑基，干巴爹。
