### ISSUE TITLE
第八章

### ISSUE THREAD

**Issue by YouKuanZeng** [mrzhqiang/studyjava-zz#40]
- 目前更新的第八章范例，不同步于电子书，请忽略。
- 关于讲课，我觉得讲解例子比讲解理论靠谱，更容易理解。
- 在你讲解例子的时候，我觉得我应该同步跟你做一遍加深印象，或者说这样也方便你更直观的看到我的问题所在。弊端在于比较耗费时间，个人想法是，跟造车那个案例一样，每一章节找一个经典的，有代表性，能比较全面的覆盖本章内容的案例来进行互动。

**Comment by mrzhqiang** [comment]
首先要确立的是用电子书，其次再就是经典案例，之后是教学形式。

**Comment by YouKuanZeng** [comment]
教学形式的话，其实跟应试教育没区别，预习，听课（讲课），复习，做题发现问题（出题，讲题），考试。
