### ISSUE TITLE
关于提问

### ISSUE THREAD

**Issue by YouKuanZeng** [mrzhqiang/studyjava-zz#56]
### 概述

- 出于mrzhqiang的对于youkuanzeng很少提问的考虑，特提出以下建议，请@mrzhqiang查看并提出不足。

### 不提问的缘故

- 不知道该问题是否应该提问。比如：mrzhqiang觉得不应该在某个问题上深究，然后youkuanzeng无法判断这个问题是否应该放过。
- youkuanzeng 非常容易捕捉情绪 ，而且会很容易把关注点陷入情绪捕捉无法自拔。
- 懒于面对问题，面对临时情绪的潜意识行为
- 害怕浪费两个人的时间，撩拨到mrzhqiang的情绪

### 解决办法
- 该解决办法只是youkuanzeng的个人浅见。请mrzhqiang认真查看，并提出不足，以便双方共同改进。
- 以后提问，按照以前的约定，只在github上提问，好处在于错开时间差，避免即时的情绪冲突。
- 建议只使用陈述语句，比如youkuanzeng的问题，应该先放过，就回复放过即可，认为需要解决，优先使用github的Issues功能回复，需要演示的就回复 并记录下来，约定时间演示。
- 不建议使用任何附带情感的语句，好吧，这样有些自私了，应该叫尽量避免使用附带情感语句，该骂的时候还是骂吧

**Comment by mrzhqiang** [comment]
阅

**Comment by YouKuanZeng** [comment]
请@mrzhqiang提议

**Comment by mrzhqiang** [comment]
***不知道该问题是否应该提问***
> 知之为知之，不知为不知，是知也。
任何疑惑，请问出来，即便是上面这句话。

***youkuanzeng无法判断这个问题是否应该放过***
> 知其难者，始于足；知其易者，了于心。
困难的地方请放过，犹豫不定的地方请询问。

***youkuanzeng 非常容易捕捉情绪***
没有情绪你还是人吗？

***懒于面对问题***
勤奋点，对于你而言，这应该首先是一件好玩的事情，其次才是职业。

***害怕浪费两个人的时间***
不提问才是浪费时间

## 关于“解决办法”的回复
可以用github，也尽量陈述句。尽量不讽刺，但是不得不说一句，你这样很令人惊讶啊，我以为我才是最玻璃心的那个。你遇到问题随便提问，最好是在这里提问，有一个解决的缓冲时间。
