### ISSUE TITLE
关于IDEA教学

### ISSUE THREAD

**Issue by YouKuanZeng** [mrzhqiang/studyjava-zz#57]
- 额，教学视频已经push，教学文件我竟然没找到

**Comment by mrzhqiang** [comment]
神马？视频push是什么情况？文件又是什么情况？分别指代什么？

**Comment by YouKuanZeng** [comment]
额，IDEA教学视频我已经通过QQ接送到了，然后教学时，用Java做的笔记注解示范，我没有找到

**Comment by mrzhqiang** [comment]
什么叫“用java做的笔记注解示范”？？？

**Comment by mrzhqiang** [comment]
QQ联系，关闭问题
