### ISSUE TITLE
新的一年，一月份想法

### ISSUE THREAD

**Issue by mrzhqiang** [mrzhqiang/studyjava-zz#63]
## 知识巩固
- 基本数据类型、进制转换
- 属性、方法以及类
- 特殊的类：枚举、接口、抽象类、内部类、嵌套类
- 从开发角度，如何设计一个类（包括特殊类）
- 重新认识对象、集合、字符串、文件，以及多线程、网络和数据库（这部分居然还没讲）

## 程序设计探讨
- 程序员的日常
- 从现实，到算法，到开发，到实现
- 分析需求，交流细节，建立雏形，完成任务

## 参与开发
- 简单的多线程——销售者与生产者
- 简单的网络——IP地址聊天室
- 简单的数据库——服务器聊天记录
- java毕业设计——（待定）

## 业界流行与热门框架
- 异步、多线程——RxJava
- 网络请求——OkHttp+Retrofit
- 数据库——SQLite、MySQL、Oracle

## 概念补习
- HTTP协议
- 线程交互

**Comment by YouKuanZeng** [comment]
OK
