### ISSUE TITLE
关于英语

### ISSUE THREAD

**Issue by YouKuanZeng** [mrzhqiang/studyjava-zz#80]
- 鉴于youkuanzeng这个渣渣英语水平
- 想把java语言常用的一些英语词汇总结出来，掌握了解
- 还是要慢慢习惯英文阅读，现在看到一页英文，觉得很受挫

**Comment by mrzhqiang** [comment]
java常用的词汇多了去！你不要陷入沼泽地带了，与其受挫，还不如耐心下来逐个使用工具翻译。熟能生巧。

**Comment by YouKuanZeng** [comment]
好的，请关闭
