### ISSUE TITLE
利用已学知识，实现一个简单的随机密码程序

### ISSUE THREAD

**Issue by mrzhqiang** [mrzhqiang/studyjava-zz#93]
### 背景
此任务来自 #92 

### 内容
- 字符集：
  - a-z （表示从a到z，下同）
  - A-Z
  - 0-9
- 随机类：
  - Random
  - Math.random
- 实现效果：
  - 输入大于0的指定长度
  - 返回指定长度的String对象
  - String对象包含随机无序的字母数字组合

**Comment by mrzhqiang** [comment]
@YouKuanZeng 请空闲时间完成任务。

**Comment by mrzhqiang** [comment]
### 任务提示
```
Math.random()
```
`Math.random`是一个方法，返回值是`double`类型，范围从`0`到`1`（但不包括`1`）

```
  Random random = new Random();
  random.nextInt(10);
```
`random.nextInt(int bound)`表示，随机生成下一个`int`数据，范围从`0`到`bound`（但不包括`bound`）

### 任务扩展
`Random`需要一个`seed`才能好好工作，它在某种情况下，不具备随机的特性（会重复出现相同值），那么你如果要近乎完全随机的类，应该去百度一下，在Java API中，有没有更好的替代类。

或者你也可以学会用IDEA工具，找到更合适的类。

**Comment by YouKuanZeng** [comment]
### 反馈
- 给我一个王炸，我要炸沉你，说实话，想了半天也没想出来怎么实现，不去网上看，根本不晓得怎么回事，看了半天才晓得，原来是这么回事。
- 扩展的任务还没解决
- 至于扩展什么的，你大概是要我学会使用解决问题的途径，有更多解决问题的方法
