### ISSUE TITLE
java收官

### ISSUE THREAD

**Issue by mrzhqiang** [mrzhqiang/studyjava-zz#96]
任何一门语言，停留在知识面上的时间，总是不能过长，或太慢。实际运用才能检验接受能力，领悟能力，以及记忆力。因此相对而言，java基本上到这里告一段落，你理解也好，不理解也罢，总归是要划上句号的。
然后我们通过一些Android上的知识，对java进行有条理的整顿，顺便研究一些好玩的东西。虽然我们时间很多，可以慢慢来，但也不能一直停留在记忆上，最起码要有真实的生产力，才能验证学习结果。
ok，1月份跑调了没关系，咱们2月份再战江湖。

**Comment by YouKuanZeng** [comment]
- read.
- 2月你不在呀你不在
