### ISSUE TITLE
栖息时已久，可敢再战江湖？

### ISSUE THREAD

**Issue by mrzhqiang** [mrzhqiang/studyjava-zz#98]
@YouKuanZeng  汝之春节已去九日，坐久懒，惰久废，岂不速速行动，好叫吾知后续，而使精彩纷呈？

**Comment by YouKuanZeng** [comment]
### 再战江湖否？
- 懒废细思极恐，吾生有涯，知无涯也，路漫漫其修远兮，时不我待矣！
### 怎战江湖呢？
- 春节已去九，荒废日久，温故而知新，故近日应首重拾旧知，再图新知。
- 春运下半场，车流高峰，下班归途，脖子腰子完全不是寄几的，欲重拾旧知有所精进，应学习与强健体魄并进，方可长久。
- 另学习与女朋友需并重，每日沉迷于给女朋友做饭下班接送不能自拔。今后时间可能会有多迁就于女友。
- 休息日久，细思前段学习，自觉学习过于慵懒，然后沉迷于跟不上进度的惶恐。依赖心强，自我解决问题欲望低。
- 每每计划赶不上变化，其实不过，自己没有把学习放在首位。
- 学习是为了过更好的生活，看到更精彩纷呈世界。
- 今年的计划有三：mooc课程十门（五门计算机课程，不论精通，但求有所得），健身，做一手好菜。
- 说这么多的自己的想法之类的废话，重点是怎么同你的想法计划相结合，完美共进。
- 还请@mrzhqiang谈谈自己的计划和想法

**Comment by mrzhqiang** [comment]
- 玩Android项目啊，先看书，慢慢看，我这边尽量多抽时间，一起搞Android
- Java应用最多的地方就是：Android和Web端，所以最好的实践就是搞它们
- 我可以搞后台接口，你用手机App来访问就是
- 上半年就这么一个小目标：搞定Android，至少做3--6个App出来

**Comment by YouKuanZeng** [comment]
- 上班年只剩下三个月咯

**Comment by mrzhqiang** [comment]
close all question
